version: '3.8'

services:
        rabbitmq_service:
                image: rabbitmq:management
                hostname: rabbit
                ports:
                        - "5672:5672"
                        - "15672:15672"
                networks:
                        - backend
        api:
                image: 10.40.71.55:5000/si_175831_api_image
                ports:
                        - "17584:44354"
                depends_on:
                        - rabbitmq_service
                networks:
                        - backend
                        - frontend
        gui:
                image: 10.40.71.55:5000/si_175831_gui_image
                ports:
                        - "1758:80"
                        #- "17583:443"
                depends_on:
                        - api
                networks:
                        - frontend
                          
networks:
        backend:
                name: si_175831_backend
                driver: overlay
        frontend:
                name: si_175831_frontend
                driver: overlay