version: '3.8'

services:
        gui:
                image: si_175831_gui_image
                ports:
                        - "1758:80"
                        - "17583:443"
        api:
                image: si_175831_api_image
                ports:
                        - "175:44354"